### ISSUE TITLE
Unable to locate the model you have specified: Ion_auth_model

### ISSUE THREAD

**Issue by adeelmughal4u** [benedmunds/CodeIgniter-Ion-Auth#892]
An uncaught Exception was encountered

Type: RuntimeException

Message: Unable to locate the model you have specified: Ion_auth_model

Filename: /home/thecvcom/public_html/system/core/Loader.php

Line Number: 314

Backtrace:

File: /home/thecvcom/public_html/application/libraries/Ion_auth.php
Line: 69
Function: model

File: /home/thecvcom/public_html/application/controllers/Auth.php
Line: 9
Function: library

File: /home/thecvcom/public_html/index.php
Line: 292
Function: require_once

**Comment by adeelmughal4u** [comment]
done, actually my editor file not was showing i is small in model... thanks

**Comment by moudarir** [comment]
Hi,

I have  the same issue. how to resolve this problem ?

thank's

**Comment by adeelmughal4u** [comment]
Use Small I of the file name in model. ion_auth_model

**Comment by hafeez551** [comment]
hi , i have applied the same solution on same problems but cannot solve the problems

**Comment by josefcampos** [comment]
Hello, I have also reviewed the case. However, it still shows the error.

**Comment by benedmunds** [comment]
Which PHP version are you on? 

Also which CodeIgniter version and Ion Auth hash?

And what OS?

**Comment by josefcampos** [comment]
> Which PHP version are you on?
> 
> Also which CodeIgniter version and Ion Auth hash?
> 
> And what OS?

Resolved! ... I am using the version of Codeigniter 3 ... the name of the model file must be capitalized:

https://www.codeigniter.com/user_guide/installation/upgrade_300.html

**Comment by benedmunds** [comment]
Hey can you try the 3 branch? It should work with CI3 out of the box.

**Comment by tpw1314** [comment]
I have the same issue in the past. Capitalizing the name of the model file solved it.

**Comment by kadivarmitesh** [comment]
Hello   How can solve these problem ?? Please Help me 

An uncaught Exception was encountered
Type: RuntimeException

Message: Unable to locate the model you have specified: Login

Filename: /opt/lampp/htdocs/CodeIgniter-3.1.9/system/core/Loader.php

Line Number: 348

Backtrace:

File: /opt/lampp/htdocs/CodeIgniter-3.1.9/application/controllers/Welcome.php
Line: 165
Function: model

File: /opt/lampp/htdocs/CodeIgniter-3.1.9/index.php
Line: 315
Function: require_once

**Comment by benedmunds** [comment]
@kadivarmitesh the models in that error arent Ion Auth models...

**Comment by kadivarmitesh** [comment]
but these whole project run in windows system properly but not execute in ubuntu ?? why

**Comment by bvrignaud** [comment]
I dont't think it's an IonAuth problem.
It's look like, you haven't give the correct right to your files.
Try to give the read right for everybody of your project directory.
It'n not a safe way but the easier.

**Comment by debasism2014** [comment]
Hello How can solve this problem? Please Help me.
An uncaught Exception was encountered
Type: RuntimeException

Message: Unable to locate the model you have specified: Login_model

Filename: /var/www/html/abc/system/core/Loader.php

Line Number: 348

Backtrace:

File: /var/www/html/abc/application/controllers/Main.php
Line: 11
Function: __construct

File: /var/www/html/abc/index.php
Line: 315
Function: require_once

**Comment by benedmunds** [comment]
@debasism2014 Ion Auth doesn't include a "Login_model".  I'd recommend posting on either the CI forums or StackOverflow for help with general CodeIgniter development.

**Comment by tpw1314** [comment]
Yes indeed I dont remember having a model file like that when I first started to use IonAuth 3 back in those days. IonAuth starts with library only. Unless they are talking about the samples codes ?

**Comment by shahabjamali45** [comment]
I getting the same issue i have tried to fix it but i am unable please look into this please 


An uncaught Exception was encountered
Type: RuntimeException

Message: Unable to locate the model you have specified: Ion_auth_model

Filename: C:\laragon\www\ciadmin\system\core\Loader.php

Line Number: 348

Backtrace:

File: C:\laragon\www\ciadmin\application\third_party\MX\Loader.php
Line: 213
Function: model

File: C:\laragon\www\ciadmin\application\libraries\Ion_auth.php
Line: 69
Function: model

File: C:\laragon\www\ciadmin\application\third_party\MX\Loader.php
Line: 173
Function: _ci_load_library

File: C:\laragon\www\ciadmin\application\modules\dashboard\controllers\Dashboard.php
Line: 25
Function: library

File: C:\laragon\www\ciadmin\index.php
Line: 315
Function: require_once

**Comment by benedmunds** [comment]
@shahab-ansari if you’re having issues with HMVC try asking on the CI forums or StackOverflow.  Also maybe try searching related issues here https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues?q=is%3Aissue+hmvc+is%3Aclosed

**Comment by sujeesh2019** [comment]
This issue is because of naming convention of model class files.
If suppose my model name is something like 'MyModelForUser.php' with class name like
class MyModelForUser extends CI_Model {

}
Issue will happen.
So based on latest code-igniter versions, its compulsory to follow the naming conventions of files and class names. So following is correct.

File name should be changed to : 'My_model_for_user.php' (Only first letter will be in caps).
class My_model_for_user extends CI_Model {

}

So when calling model in controller, It should be some thing like:
$this->load->model(array('my_model_for_user'));

So change all file name and class names like this.
It will work.
